#!/bin/sh

# Resizer mmcblk1p2
resize2fs /dev/mmcblk1p2

# Anti EXT4 Readonly
sed -i 's/exit 0/mount -o remount,rw \/rom\nmount -o remount,rw \/dev\/mmcblk1p2\nexit 0/g' /etc/rc.local

# luci language
uci set luci.main.lang=zh_cn
uci commit luci

# argon
uci batch <<EOF
set argon.@global[0].primary='#1c77ff'
set argon.@global[0].dark_primary='#1c77ff'
set argon.@global[0].blur='10'
set argon.@global[0].blur_dark='10'
set argon.@global[0].transparency='0.5'
set argon.@global[0].transparency_dark='0.5'
set argon.@global[0].mode='normal'
set argon.@global[0].online_wallpaper='none'
EOF
uci commit argon

# limited cpufreq for v1.0 bug
uci batch <<EOF
set cpufreq.cpufreq.governor0='schedutil'
set cpufreq.cpufreq.minfreq0='96000'
set cpufreq.cpufreq.maxfreq0='1488000'
EOF
uci commit cpufreq

# ttyd autologin
#uci batch <<EOF
#set ttyd.@ttyd[0].command='/bin/login -f root'
#EOF
#uci commit ttyd
#set ttyd.@ttyd[0].interface='@lan'

# turboacc bbr_cca is on
#uci set turboacc.config.bbr_cca='1'
#uci commit turboacc

# netspeedtest homebox is on
#uci set netspeedtest.homebox.enabled='1'
#uci set netspeedtest.speedtestiperf3.enabled='1'
#uci commit netspeedtest

# system
uci batch <<EOF
set system.@system[0].hostname='OneCloud'
set system.@system[0].timezone='JST-9'
set system.@system[0].zonename=''Asia/Tokyo'
delete system.ntp.enable_server
add_list system.ntp.server="cn.ntp.org.cn"
add_list system.ntp.server="edu.ntp.org.cn"
add_list system.ntp.server="ntp.ntsc.ac.cn"
add_list system.ntp.server="ntp.tuna.tsinghua.edu.cn"
set system.ntp.use_dhcp='0'
EOF
uci commit system

# fix distfeeds
#cat << "EOF" > /etc/opkg/distfeeds.conf
#src/gz immortalwrt_base https://mirror.nju.edu.cn/immortalwrt/snapshots/packages/arm_cortex-a5_vfpv4/base
#src/gz immortalwrt_luci https://mirror.nju.edu.cn/immortalwrt/snapshots/packages/arm_cortex-a5_vfpv4/luci
#src/gz immortalwrt_packages https://mirror.nju.edu.cn/immortalwrt/snapshots/packages/arm_cortex-a5_vfpv4/packages
#src/gz immortalwrt_routing https://mirror.nju.edu.cn/immortalwrt/snapshots/packages/arm_cortex-a5_vfpv4/routing
#src/gz immortalwrt_telephony https://mirror.nju.edu.cn/immortalwrt/snapshots/packages/arm_cortex-a5_vfpv4/telephony
#EOF

cat << "EOF" > /etc/opkg/distfeeds.conf
src/gz immortalwrt_base https://downloads.immortalwrt.org/snapshots/packages/arm_cortex-a5_vfpv4/base
src/gz immortalwrt_luci https://downloads.immortalwrt.org/snapshots/packages/arm_cortex-a5_vfpv4/luci
src/gz immortalwrt_packages https://downloads.immortalwrt.org/snapshots/packages/arm_cortex-a5_vfpv4/packages
src/gz immortalwrt_routing https://downloads.immortalwrt.org/snapshots/packages/arm_cortex-a5_vfpv4/routing
src/gz immortalwrt_telephony https://downloads.immortalwrt.org/snapshots/packages/arm_cortex-a5_vfpv4/telephony
EOF

cat << "EOF" > /etc/opkg.conf
dest root /
dest ram /tmp
lists_dir ext /var/opkg-lists
option overlay_root /overlay
option check_signature
arch all 100
arch arm_cortex-a5_neon-vfpv4 200
arch arm_cortex-a5_vfpv4 300
EOF

# firewall
uci batch <<EOF
delete firewall.@defaults[0].syn_flood='0'
set firewall.@defaults[0].input='ACCEPT'
set firewall.@defaults[0].forward='ACCEPT'
set firewall.@defaults[0].fullcone6='1'
delete firewall.@zone[0].network
add_list firewall.@zone[0].network='lan'
add_list firewall.@zone[0].network='lan2'
add_list firewall.@zone[0].network='lan3'
add_list firewall.@zone[0].network='lan6'
EOF
uci commit firewall
/etc/init.d/firewall restart

# dnsmasq
# dhcp.@dnsmasq[0].boguspriv      # 唯一授权
# dhcp.@dnsmasq[0].dns_redirect   # DNS 重定向
# dhcp.@dnsmasq[0].filterwin2k
# dhcp.@dnsmasq[0].authoritative
# dhcp.@dnsmasq[0].readethers
# dhcp.@dnsmasq[0].resolvfile
# dhcp.@dnsmasq[0].nonwildcard
# dhcp.@dnsmasq[0].filter_a
# dhcp.@dnsmasq[0].nonegcache='1'
# dhcp.@dnsmasq[0].cachesize='10000'
# dhcp.@dnsmasq[0].filter_aaaa='1'
# dhcp.@dnsmasq[0].server='1.1.1.1#443'
# dhcp.@dnsmasq[0].noresolv='1'
# dhcp.@dnsmasq[0].nohosts='1'
# dhcp.@dnsmasq[0].interface='lan'   # 监听接口
# dhcp.@dnsmasq[0].dnsseccheckunsigned='0'   # DNSSEC 检查未签名
# dhcp.@dnsmasq[0].filter_aaaa='1'  # 过滤 IPv6 AAAA 记录
# dhcp.@dnsmasq[0].nonegcache='1'   # 禁用无效信息缓存

uci batch <<EOF
delete dhcp.@dnsmasq[0].boguspriv
delete dhcp.@dnsmasq[0].dns_redirec
set dhcp.@dnsmasq[0].interface='lan'
set dhcp.@dnsmasq[0].dnsseccheckunsigned='0'
set dhcp.@dnsmasq[0].filter_aaaa='1'
set dhcp.@dnsmasq[0].nonegcache='1'
delete dhcp.lan.dhcpv6
delete dhcp.lan.ra
delete dhcp.lan.ra_slaac
delete dhcp.lan.ra_flags
delete dhcp.lan.ndp
set dhcp.lan.ignore='1'
set dhcp.lan.dynamicdhcp='0'
set dhcp.@dnsmasq[0].server='127.0.0.1#5335'
EOF
uci commit dhcp
/etc/init.d/dnsmasq restart
#set dhcp.@dnsmasq[0].serversfile='/etc/dnsmasq.d/accelerated-domains.china.conf'

#mosdns
uci batch <<EOF
set mosdns.config.enabled='1'
set mosdns.config.listen_port='5335'
set mosdns.config.geo_auto_update='1'
set mosdns.config.geo_update_week_time='1'
set mosdns.config.geo_update_day_time='2'
set mosdns.config.dump_file='1'
set mosdns.config.concurrent='2'
set mosdns.config.custom_local_dns='1'
set mosdns.config.dns_leak='1'
set mosdns.config.bootstrap_dns='8.8.8.8'
set mosdns.config.local_dns='114.114.114.114'
set mosdns.config.remote_dns='udp://127.0.0.53:53'
set mosdns.config.enable_ecs_remote='0'
set mosdns.config.dump_interval='3600'
EOF
uci commit mosdns

# network config
uci batch <<EOF
delete network.lan.ip6assign
delete network.globals.ula_prefix
set network.lan.gateway='192.168.177.1'
set network.lan.dns='127.0.0.1'
set network.lan6=interface
set network.lan6.proto='dhcpv6'
set network.lan6.device='@lan'
set network.lan6.reqaddress='try'
set network.lan6.reqprefix='auto'
set network.lan6.dns='::1'
EOF
uci commit network
/etc/init.d/network restart

#set network.lan2=interface
#set network.lan2.proto='static'
#set network.lan2.device='br-lan'
#set network.lan2.ipaddr='192.168.177.98'
#set network.lan2.netmask='255.255.255.0'
#set network.lan2.gateway='192.168.177.1'
#set network.lan2.metric='40'
#set network.lan2.dns='127.0.0.1'
#set network.lan3=interface
#set network.lan3.proto='static'
#set network.lan3.device='br-lan'
#set network.lan3.ipaddr='192.168.177.99'
#set network.lan3.netmask='255.255.255.0'
#set network.lan3.gateway='192.168.177.1'
#set network.lan3.dns='127.0.0.1'
#set network.lan3.metric='40'


# dnscrypt-proxy2 setting
sed -i 's/START=18/START=99/g' /etc/init.d/dnscrypt-proxy
#sed -i 's/127.0.0.53:53/127.0.0.1:5335/g' /etc/dnscrypt-proxy2/dnscrypt-proxy.toml
sed -i 's/ipv6_servers = false/ipv6_servers = true/g' /etc/dnscrypt-proxy2/dnscrypt-proxy.toml
sed -i 's/odoh_servers = false/odoh_servers = true/g' /etc/dnscrypt-proxy2/dnscrypt-proxy.toml
sed -i 's/http3 = false/http3 = true/g' /etc/dnscrypt-proxy2/dnscrypt-proxy.toml
sed -i 's/cache_size = 4096/cache_size = 10240/g' /etc/dnscrypt-proxy2/dnscrypt-proxy.toml
sed -i 's/127.0.0.1:9050/127.0.0.1:1070/g' /etc/dnscrypt-proxy2/dnscrypt-proxy.toml
#sed -i 's/127.0.0.1:8888/127.0.0.1:1101/g' /etc/dnscrypt-proxy2/dnscrypt-proxy.toml
sed -i 's/# proxy/proxy/g' /etc/dnscrypt-proxy2/dnscrypt-proxy.toml
#sed -i 's/# http_proxy/http_proxy/g' /etc/dnscrypt-proxy2/dnscrypt-proxy.toml
#sed -i 's/# blocked_names_file/blocked_names_file/g' /etc/dnscrypt-proxy2/dnscrypt-proxy.toml

# 
uci commit 

# crontabs
#echo '* 4 * * 1  wget --no-check-certificate -O /etc/dnsmasq.d/accelerated-domains.china.conf "https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf"' >> /etc/crontabs/root

exit 0
