name: Sync packages

on:
  push:
    paths:
      - '.github/workflows/syncore.yml'
      - '.github/diy/main.sh'
  schedule:
    - cron: 0 */4 * * *
  repository_dispatch:
  workflow_dispatch:
    inputs:
      packages:
        description: 'OneCloud Core'
        required: false
        default: 'false'	

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id || ! github.event.sender.id
    runs-on: ubuntu-latest

    name: Update ${{matrix.target}}
    strategy:
      fail-fast: false
      matrix:
        target: [main]

    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        fetch-depth: 0

    - name: Initialization environment
      run : |
        git config --global user.email "0xACE8@users.noreply.github.com"
        git config --global user.name "0xACE8"
        sudo timedatectl set-timezone "America/Los_Angeles"
        
    - name: Clone packages
      run: |
        cd $GITHUB_WORKSPACE
        chmod +x .github/diy/${{matrix.target}}.sh
        git clone -b ${{matrix.target}} https://github.com/0xACE8/0n3cl0ud.git ${{matrix.target}}
        cd ${{matrix.target}}
        git rm -r --cache * >/dev/null 2>&1 &
        rm -rf `find ./* -maxdepth 0 -type d ! -name "diy"` >/dev/null 2>&1
        $GITHUB_WORKSPACE/.github/diy/${{matrix.target}}.sh

    - name: Upload
      env: 
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
        if [ -e $GITHUB_WORKSPACE/argon ]; then
          cp -r $GITHUB_WORKSPACE/argon $GITHUB_WORKSPACE/${{matrix.target}}
        fi
        if [ -e $GITHUB_WORKSPACE/0n3cl0ud-wifi.c0nf ]; then
          cp $GITHUB_WORKSPACE/0n3cl0ud-wifi.c0nf $GITHUB_WORKSPACE/${{matrix.target}}
        fi
        if [ -e $GITHUB_WORKSPACE/0n3cl0ud.c0nf ]; then
          cp $GITHUB_WORKSPACE/0n3cl0ud.c0nf $GITHUB_WORKSPACE/${{matrix.target}}
        fi
        if [ -e $GITHUB_WORKSPACE/99-init-settings ]; then
          cp $GITHUB_WORKSPACE/99-init-settings $GITHUB_WORKSPACE/${{matrix.target}}
        fi
        if [ -e $GITHUB_WORKSPACE/banner ]; then
          cp $GITHUB_WORKSPACE/banner $GITHUB_WORKSPACE/${{matrix.target}}
        fi
        if [ -e $GITHUB_WORKSPACE/burn.sh ]; then
          cp $GITHUB_WORKSPACE/burn.sh $GITHUB_WORKSPACE/${{matrix.target}}
        fi
        if [ -e $GITHUB_WORKSPACE/d1y-p4r71.sh ]; then
          cp $GITHUB_WORKSPACE/d1y-p4r71.sh $GITHUB_WORKSPACE/${{matrix.target}}
        fi
        if [ -e $GITHUB_WORKSPACE/d1y-p4r72.sh ]; then
          cp $GITHUB_WORKSPACE/d1y-p4r72.sh $GITHUB_WORKSPACE/${{matrix.target}}
        fi
        if [ -e $GITHUB_WORKSPACE/f33d5.c0nf.d3f4ult ]; then
          cp $GITHUB_WORKSPACE/f33d5.c0nf.d3f4ult $GITHUB_WORKSPACE/${{matrix.target}}
        fi
        cd $GITHUB_WORKSPACE/${{matrix.target}}
        if git status --porcelain | grep .; then
          git add .
          git commit -am "update $(date '+%Y-%m-%d %H:%M:%S')"
          git push --quiet "https://${{ secrets.ACCESS_TOKEN }}@github.com/0xACE8/0n3cl0ud.git" HEAD:${{matrix.target}}
        else
          echo "nothing to commit"
          exit 0
        fi || exit 0

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        repository: ${{ github.repository }}
        delete_workflow_pattern: syncore.yml
        retain_days: 1
        keep_minimum_runs: 1

 
